name: Deploy (dummy)

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' &&  github.event.workflow_run.head_branch == 'staging' }}
    steps:
      - name: Dummy deploy (staging)
        run: echo "Traceback (most recent call last):"
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' &&  github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Dummy deploy (production)
        run: echo "Hello, world!"
